spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://localhost:3306/gogopet?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
#  sql:
#    init:
#      mode: always
#      schema-locations: classpath:sql/DB_by_cursor.sql
#      continue-on-error: true