spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://localhost:3306/gogopet?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#  sql:
#    init:
#      mode: always
#      schema-locations: classpath:sql/DB_by_cursor.sql
#      continue-on-error: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret: 8Zz5tw0Ionm3XPZZfN0NOml3z9FMfmpgXwovR9fp6ryDIoGRM8EPHAB6iHsc0fb
  expiration: 86400  # 24小时，单位：秒

upload:
  path: uploads
  url-prefix: http://localhost:8080/uploads

# DeepSeek API配置
deepseek:
  api:
    key: sk-2ce4505522d1410893479f4a57335474
    url: https://api.deepseek.com/v1/chat/completions