spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://localhost:3306/gogopet?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: [your_mysql_username]
    password: [your_mysql_password]
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret: 8Zz5tw0Ionm3XPZZfN0NOml3z9FMfmpgXwovR9fp6ryDIoGRM8EPHAB6iHsc0fb
  expiration: 86400  # 24小时，单位：秒

upload:
  path: uploads
  url-prefix: http://localhost:8080/uploads

# DeepSeek API配置
deepseek:
  api:
    key: [your_deepseek_api_key]
    url: https://api.deepseek.com/v1/chat/completions